name: Azure artifacts dev publishing
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update the runner with packages
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Install Azure cli modules
        run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Check Azure CLI and powershell version installed
        run: |
          echo "Powershell version is `pwsh --version`"
          echo "Azure cli version is `az --version`"
