name: Azure artifacts dev publishing
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update the runner with packages
        run: |
          sudo apt-get update

      - name: Install Azure cli modules
        run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
